openapi: "3.0.0"
info:
  version: 1.0.0
  title: Grunner
  license:
    name: MIT
#servers:
#  - url: http://grunner.io/v1
paths:
  /jobs:
    get:
      summary: List all jobs for user
      operationId: listJobs
      tags:
        - list
        - jobs
      parameters:
        - name: status
          in: query
          description: Only list jobs of specified status
          required: false
          schema:
            $ref: '#/components/schemas/JobStatus'
      responses:
        200:
          description: The list of jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/JobSummary"
        default:
          description: The error detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
    post:
      summary: Create a job
      operationId: createJob
      tags:
        - create
        - jobs
      requestBody:
        description: The script to execute
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        204:
          description: ID of new job
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobSummary"
        default:
          description: The error detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"

components:
  schemas:
    JobId:
      description: Unique identifier of a job
      type: string
    JobStatus:
      type: string
      description: Possible states of a job
      enum:
        - Pending
        - Cancelled
        - Executing
        - Failed
        - Completed
    JobSummary:
      description: Summary description of a job
      properties:
        id:
          $ref: '#/components/schemas/JobId'
        status:
          $ref: '#/components/schemas/JobStatus'
    JobInfo:
      description: All info of a job
      allOf:
        - $ref: '#/components/schemas/JobSummary'
        - type: object
          properties:
            submitDate:
              description: The time at which the job was submitted
              type: string
              format: date-time
            script:
              description: The script to execute
              type: string
            owner:
              description: Username of the submitter
              type: string
    ErrorDetail:
      description: Summary error
      properties:
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

security:
  - BasicAuth:
      - read
      - write
