openapi: "3.0.0"
info:
  version: 1.0.0
  title: Grunner
  license:
    name: MIT
paths:
  /batches:
    get:
      summary: List user's batch & latest status
      operationId: listBatches
      responses:
        200:
          description: The list of (matching) batches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BatchStatusUpdate"
    post:
      summary: Submit a new batch
      operationId: enqueueBatch
      requestBody:
        description: The script to execute
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        202:
          description: Unique identifier of new batch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchId"
        400:
          description: The script was not syntactically valid
  /batches/{batchId}:
    delete:
      summary: Cancel a batch
      operationId: cancelBatch
      parameters:
        - name: batchId
          in: path
          required: true
          description: Id of batch to cancel
          schema:
            $ref: '#/components/schemas/BatchId'
      responses:
        204:
          description: Batch was cancelled
        403:
          description: Batch was not 'Pending' and could not cancelled
        404:
          description: Specified batch could not be found within user scope
  /batches/{batchId}/results:
    get:
      summary: List user's batch & latest status
      operationId: batchResults
      parameters:
        - name: batchId
          in: path
          required: true
          description: Id of batch for which to retrieve the results
          schema:
            $ref: '#/components/schemas/BatchId'
      responses:
        200:
          description: The batch's results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchResult"
        404:
          description: The batch is not in 'Completed' nor in 'Failed' status and thus has no result.

components:
  schemas:
    BatchId:
      description: Unique identifier of a batch
      type: string
      format: uuid
    BatchStatus:
      type: string
      description: Possible states of a batch
      enum:
        - Pending
        - Executing
        - Completed
        - Cancelled
        - Failed
    BatchResult:
      description: All info of a batch
      properties:
        batch-id:
          $ref: '#/components/schemas/BatchId'
        status:
          description: The batch's final status, either 'Completed' or 'Failed'
          $ref: '#/components/schemas/BatchStatus'
        timestamp:
          description: The time at which the batch finished
          type: string
          format: date-time
        results:
          description: The result of the batch. This field may be omitted if the script returned 'null'
          type: string
    BatchStatusUpdate:
      properties:
        batch-id:
          $ref: '#/components/schemas/BatchId'
        status:
          $ref: '#/components/schemas/BatchStatus'
        timestamp:
          description: The time at which the batch status last changed
          type: string
          format: date-time
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

security:
  - BasicAuth:
      - read
      - write
