spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/grunner
    username: sa
    password:
    driverClassName: org.h2.Driver

grunner:
  loop:
    delay: 4000
