#springdoc:
#  version: '@springdoc.version@'
#  api-docs:
#    groups:
#      enabled: true
#  swagger-ui:
#    path: /swagger-ui.html
#    display-request-duration: true
#    groups-order: DESC
#    operationsSorter: method
#  show-actuator: true
#  group-configs:
#    - group: users
#      packages-to-scan: ca.rbon.grunner